/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package percobaan;

/**
 *
 * @author wanvy
 */
public class FUtama extends javax.swing.JFrame {

    /**
     * Creates new form FUtama
     */
    public FUtama() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btMahasiswa = new javax.swing.JButton();
        btDosen = new javax.swing.JButton();
        btLogout = new javax.swing.JButton();
        btKuliah = new javax.swing.JButton();
        btUser = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btMahasiswa.setText("Form Mahasiswa");
        btMahasiswa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btMahasiswaActionPerformed(evt);
            }
        });
        getContentPane().add(btMahasiswa, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 80, -1, -1));

        btDosen.setText("Form Dosen");
        getContentPane().add(btDosen, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 120, 120, -1));

        btLogout.setText("Log Out");
        btLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLogoutActionPerformed(evt);
            }
        });
        getContentPane().add(btLogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 160, 290, -1));

        btKuliah.setText("Form Kuliah");
        getContentPane().add(btKuliah, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 120, 100, -1));

        btUser.setText("Form User");
        btUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btUserActionPerformed(evt);
            }
        });
        getContentPane().add(btUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 80, 100, -1));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        jLabel1.setText("Menu Utama");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btMahasiswaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btMahasiswaActionPerformed
        // TODO add your handling code here: ini untuk FMahasiswa
        FMahasiswa formMahasiswa = new FMahasiswa();
        formMahasiswa.setVisible(true);
        
    }//GEN-LAST:event_btMahasiswaActionPerformed

    private void btLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLogoutActionPerformed
        // TODO add your handling code here: ini untuk LogOut
        FLogin formLogin = new FLogin();
        formLogin.setVisible(true);
        dispose();
    }//GEN-LAST:event_btLogoutActionPerformed

    private void btUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btUserActionPerformed
        // TODO add your handling code here:
        FUser formUser = new FUser();
        formUser.setVisible(true);
    }//GEN-LAST:event_btUserActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FUtama().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btDosen;
    private javax.swing.JButton btKuliah;
    private javax.swing.JButton btLogout;
    private javax.swing.JButton btMahasiswa;
    private javax.swing.JButton btUser;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
